version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Building the project..."

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Running tests..."

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Deploying the project..."

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold_for_approval:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold_for_approval