version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - run: echo "Building project"

  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - run: echo "Running tests"

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - run: echo "Deploying project"

workflows:
  build_and_test:
    jobs:
      - build
      - test

  build_and_deploy:
    jobs:
      - build
      - deploy