version: 2.1

jobs:
  a1:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: A1
          command: |
            echo "Running job A1"
            sleep 1

  a2:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: A2 (Fail)
          command: |
            echo "Running job A2"
            sleep 1
            exit 1

  a3:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: A3
          command: |
            echo "Running job A3"
            sleep 1

  b1:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: B1
          command: |
            echo "Running job B1"
            sleep 1

  b2:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: B2
          command: |
            echo "Running job B2"
            sleep 1

  b3:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: B3
          command: |
            echo "Running job B3"
            sleep 1

workflows:
  test-workflow:
    jobs:
      - a1
      - b1
      - a2:
          requires:
            - a1
      - a3:
          requires:
            - a2
      - b2:
          requires:
            - b1
      - b3:
          requires:
            - b2
