version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@dev:19e80d708e9a7720d87448eac048372270ff607d
workflows:
  use-my-orb:
    jobs:
      - continuation/continue:
          configuration_path: .circleci/continue_config.yml
          resource_class: "large"
