version: 2.1

jobs:
  job1:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Running Job 1"
          command: echo "job1"
  job2:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Running Job 1"
          command: echo "running job 2"
    

workflows:
  version: 2
  build_and_test:
    jobs: 
      - approval_job:
          type: approval
          context: restricted-context
      - job2:
          requires:
            - approval_job
          context: restricted-context