version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@latest
workflows:
  use-my-orb:
    jobs:
      - continuation/continue:
          configuration_path: .circleci/continue_config.yml
          resource_class: "large"
