version: 2.1

parameters:
  pipeline.git.bla:
    type: string
    default: ""

jobs:
  job1:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Running Job"
          command: |
            echo "<< pipeline.git.bla >>"

workflows:
  version: 2
  build_and_test:
    jobs:
      - job1
