version: 2.1

executors:
  base-runner:
    docker:
      - image: cimg/base:stable

jobs:
  job-fast-fail:
    executor: base-runner
    steps:
      - run:
          name: "Fail fast"
          command: |
            echo "Simulating a rapid failure..."
            sleep 5
            exit 1

  job-long-run:
    executor: base-runner
    steps:
      - run:
          name: "Simulate long process"
          command: |
            echo "Starting long running job..."
            sleep 300 # Runs for 5 minutes

workflows:
  test-rerun-workflow:
    jobs:
      - job-fast-fail
      - job-long-run