version: 2.1

parameters:
  package-type:
    type: string
    default: "GC"

executors:
  default-executor:
    docker:
      - image: circleci/python:3.9

jobs:
  conditional-job:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Perform Conditional Logic
          command: echo "This job runs based on complex conditions."

workflows:
  version: 2
  conditional_workflow:
    when:
      condition:
        or:
          - and:
              - equal: [ api, << pipeline.trigger_source >> ]
              - equal: [ GC, << pipeline.parameters.package-type >> ]
          - equal: [ webhook, << pipeline.trigger_source >> ]
    jobs:
      - conditional-job