version: 2.1

jobs:
  A:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Running Job A"

  B:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Running Job B"

  C:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Running Job C"

workflows:
  version: 2
  workflow:
    jobs:
      - A:
          filters:
            branches:
              only: master
      - B:
          filters:
            branches:
              only: master
      - C:
          requires:
            - A
            - B
