version: 2.1

jobs:
  job_a:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Step A1
          command: |
            echo "Running step A1"
            exit 1
      - run:
          name: Step A2 (Fail)
          command: |
            echo "Running step A2"
            sleep 30
      - run:
          name: Step A3
          command: |
            echo "Running step A3"
            sleep 30

  job_b:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Step B1
          command: |
            echo "Running step B1"
            sleep 30
      - run:
          name: Step B2
          command: |
            echo "Running step B2"
            sleep 30
      - run:
          name: Step B3
          command: |
            echo "Running step B3"
            sleep 30

workflows:
  test:
    jobs:
      - job_a
      - job_b
