version: 2.1
jobs:
  parent_job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Generate a file
          command: echo "Hello from parent job" > parent_job_file.txt
      - persist_to_workspace:
          root: .
          paths:
            - parent_job_file.txt

  child_job:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Use the file from parent job
          command: cat ./parent_job_file.txt

workflows:
  version: 2
  build_and_use_file:
    jobs:
      - parent_job
      - child_job:
          requires:
            - parent_job
