  version: 2.1
  setup: true
  orbs:
    continuation: circleci/continuation@0.4.0
  workflows:
    use-my-orb:
      jobs:
        - continuation/continue:
            configuration_path: "./continue_config.yml"
            parameters: '{"image-tag":"current"}'
