version: 2.1

jobs:
  job1:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Running Job 1"
          command: echo $my_restricted_env
    
  approval_job:
    type: approval

workflows:
  version: 2
  build_and_test:
    jobs:
      - approval_job
      - job1:
          context: restricted-context
          requires:
            - approval_job