version: 2.1

jobs:
  job1:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Running Job 1"
          command: |
            echo "Job 1."

  job2:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Running Job 2"
          command: |
            echo "<< pipeline.git.tag >>"

workflows:
  version: 2
  build_and_test:
    when:
      not:
        equal: ["<< pipeline.git.tag >>", ""]
    jobs:
      - job1
  other:
    jobs:
      - job2
