version: 2.1

setup: true
orbs:
  continuation: circleci/continuation@0.4

jobs:
  setup:
    executor: continuation/default
    steps:
      - run: echo "Here"
      - continuation/continue:
          configuration_path: .circleci/continue_config.yml


workflows:
  setup:
    jobs:
      - setup