version: 2.1

jobs:
  job1:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Running Job"
          command: |
            echo "<< pipeline.git.tag >>"

workflows:
  version: 2
  build_and_test:
    jobs:
      - job1
