  version: 2.1
  setup: true
  orbs:
    path-filtering: circleci/path-filtering@dev:aed133a147a453f89ef92001a73420f04db01679
    
  jobs:
    env-var-test:
      machine:
        image: ubuntu-2204:2023.02.1
      environment:
        LOCAL_SEED_ADDRESS: '0x21DF875603Ba765a15F9ae20e633D2DAe42952d9'
      steps:
        - checkout
        - run: echo $LOCAL_SEED_ADDRESS
  
  workflows:
    use-my-orb:
      jobs:
        - env-var-test
        - path-filtering/filter:
            base-revision: main
            config-path: .circleci/continue_config.yml
            mapping: |
              ./* static-checks true


