version: 2.1

jobs:
  test:
    type: no-op

  build:
    type: no-op

  release:
    type: no-op  

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Sleep for 30 seconds
          command: sleep 90

workflows:
  main-workflow:
    jobs:
      - test
      - build
      - deploy:
          serial-group: 'a'
          requires:
            - test
            - build
      - release:
          serial-group: 'a'
          requires: 
            - deploy