version: 2.1

jobs:
  static-checks:
    docker:
      - image: cimg/node:16.10
    environment:
      LOCAL_SEED_ADDRESS: "0x21DF875603Ba765a15F9ae20e633D2DAe42952d9"
    steps:
      - checkout
      - run: echo $LOCAL_SEED_ADDRESS

workflows:
  static-checks:
    jobs:
      - static-checks
