version: 2.1

parameters:
  static-checks-1:
    type: boolean
    default: false

jobs:
  static-checks:
    docker:
      - image: cimg/node:16.10
    environment:
      LOCAL_SEED_ADDRESS: '0x21DF875603Ba765a15F9ae20e633D2DAe42952d9'
      OTHER_THING: "0x21DF875603Ba765a15F9ae20e633D2DAe42952d9"
      SOME_OTHER: "asabc"
      SOME_OTHERs: 'asabc'
    steps:
      - checkout
      - run: echo $LOCAL_SEED_ADDRESS
      - run: echo $SOME_OTHERs
      - run: echo $OTHER_THING
      - run: echo $SOME_OTHER

workflows:
  static-checks:
    jobs:
      - static-checks
